#!/bin/bash
#
# Regenerate Low-Quality Image Placeholders (assets/js/lqip.js).
#
# Run this whenever you ADD, REPLACE, or REMOVE a photo in assets/images/.
# It scans the photo pages for the images they use, makes a tiny 16px blurred
# JPEG of each, base64-inlines them into assets/js/lqip.js, and bumps the
# lqip.js?v= cache version so browsers fetch the new file.
#
# Usage:  ./tools/gen-lqip.sh
# Requires: macOS `sips` (already used by the project).
#
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root

OUT="assets/js/lqip.js"
PAGES=(zh/index.html zh/about.html zh/philosophy.html zh/campus.html)
TMP="$(mktemp -t lqip).jpg"
trap 'rm -f "$TMP"' EXIT

# Unique photo filenames referenced on the photo pages, from both src= and
# srcset= (the hero uses <picture><source srcset> for its responsive variants,
# and it gets blur-up too).
files=$(grep -rhoE '(src|srcset)="\.\./assets/images/[a-z0-9._-]+\.jpg"' "${PAGES[@]}" \
  | sed 's#.*/##; s/"//' | sort -u || true)

{
  echo "/* Low-Quality Image Placeholders — tiny blurred previews shown while the"
  echo "   full photo loads. Auto-generated by tools/gen-lqip.sh — do not edit. */"
  echo "window.LQIP = {"
} > "$OUT"

n=0
for name in $files; do
  src="assets/images/$name"
  [ -f "$src" ] || { echo "  ! missing $src (referenced but not found) — skipped" >&2; continue; }
  sips -Z 16 -s formatOptions 45 "$src" --out "$TMP" >/dev/null 2>&1
  b64=$(base64 -i "$TMP" | tr -d '\n')
  printf '  "%s": "data:image/jpeg;base64,%s",\n' "$name" "$b64" >> "$OUT"
  n=$((n + 1))
done
echo "};" >> "$OUT"

# Bump the lqip.js?v= cache version on the photo pages.
cur=$(grep -ohE 'lqip\.js\?v=[0-9]+' "${PAGES[@]}" | grep -oE '[0-9]+' | sort -n | tail -1)
next=$(( ${cur:-0} + 1 ))
sed -i '' "s/lqip\.js?v=[0-9]*/lqip.js?v=$next/" "${PAGES[@]}"

echo "✓ Wrote $OUT ($n placeholders) and bumped lqip.js → v=$next"
echo "  Remember to commit assets/js/lqip.js and the updated pages."
